# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 220467d69fc83ff71fb3d45c28a076be51ae5576170e39943f83c8f9cd27712f9bb3f43ce571630f538d4b95946add9b6bf91c9d20d8c2d40a97f212f7970899

test:
  secret_key_base: 676a4b4893dcf02a0987e6667c4df0e80e80798c54d080331beaeda67c75ab0a63620bc1b98fec4bc57bed0cd97fa04d587cb8e6819eefbcf813f23d418c152d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
